# # Expose ArgoCD Server
# apiVersion: v1
# kind: Service
# metadata:
#   name: service 
#   namespace: carservice
# spec:
#   type: NodePort
#   ports:
#     - name: http
#       port: 80
#       targetPort: 80
#       nodePort: 30007
#     - name: https
#       port: 443
#       targetPort: 80
#       nodePort: 30008
#   selector:
#     app: backend-api